const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const model = require("../js/hotel-price-trends-model.js");
// Generated by the export's own calculator (app/daily_trends.py), so the UI is tested against the real payload shape.
const fixture = require("./fixtures/hotel-price-daily-trend.json");

const CORE = [30109, 39175, 12568, 28637, 9691];
const region = (dailyTrend, overrides = {}) => ({
  code: "noboribetsu-onsen", name: "登別温泉", cohort_version: "noboribetsu-v1", expected_core_count: 5,
  properties: CORE.map((hotel_no) => ({hotel_no, name: `H${hotel_no}`, role: "core"})),
  rates: CORE.map((hotel_no) => ({hotel_no, stay_date: "2026-10-12", meal_type: "two_meals", min_price_yen: 20000, plan_count: 1, status: "success"})),
  ...(dailyTrend === undefined ? {} : {daily_trend: dailyTrend}),
  ...overrides
});
const clone = (value) => JSON.parse(JSON.stringify(value));

test("market and facility views take all eight exported points without recalculating them", () => {
  const view = model.dailyTrendView(region(fixture.valid));
  assert.equal(view.status, "valid");
  assert.deepEqual(view.market.points.map((point) => point.label), ["7日前", "6日前", "5日前", "4日前", "3日前", "2日前", "昨日", "今日"]);
  assert.deepEqual(view.market.points.map((point) => point.value), fixture.valid.market.series.map((point) => point.change_pct));
  assert.deepEqual(view.market.points.map((point) => point.snapshotDate), fixture.valid.snapshot_dates);
  assert.equal(view.market.changePct, fixture.valid.market.series.at(-1).change_pct);
  assert.deepEqual(view.market.direction, fixture.valid.market.trend);
  assert.deepEqual([view.market.validCount, view.market.expectedCount], [4, 5]);
  const selected = view.facilities.find((facility) => facility.hotel_no === 30109);
  const exported = fixture.valid.facilities.find((facility) => facility.hotel_no === 30109);
  assert.deepEqual(selected.points.map((point) => point.value), exported.series.map((point) => point.change_pct));
  assert.equal(selected.changePct, 8);
  assert.equal(selected.direction.label, "上昇傾向");
  assert.equal(selected.commonStayDates, 12);
  assert.equal(model.trendSegments(view.market.points).length, 1);
  assert.equal(model.trendSegments(view.market.points)[0].length, 8);
});

test("facilities follow the cohort display order and keep the three coverage levels", () => {
  const view = model.dailyTrendView(region(fixture.reference));
  assert.deepEqual(view.facilities.map((facility) => facility.hotel_no), CORE);
  const byNo = new Map(view.facilities.map((facility) => [facility.hotel_no, facility]));
  assert.equal(byNo.get(28637).coverage, "valid");
  assert.equal(byNo.get(12568).coverage, "reference");
  assert.equal(byNo.get(12568).changePct, 4);
  assert.equal(view.status, "reference");
  assert.equal(view.market.status, "reference");
  assert.equal(view.market.validCount, 3);
});

test("only production labels are passed through for direction", () => {
  const view = model.dailyTrendView(region(fixture.valid));
  const labels = new Set([view.market.direction, ...view.facilities.map((facility) => facility.direction)].filter(Boolean).map((direction) => direction.label));
  for (const label of labels) assert.ok(["上昇傾向", "横ばい", "低下傾向"].includes(label), label);
});

test("an insufficient facility draws no line and hides the exported label", () => {
  const view = model.dailyTrendView(region(fixture.valid));
  const thin = view.facilities.find((facility) => facility.hotel_no === 9691);
  const exported = fixture.valid.facilities.find((facility) => facility.hotel_no === 9691);
  assert.equal(exported.trendCoverage.status, "insufficient");
  assert.ok(exported.series.some((point) => point.change_pct != null), "fixture keeps values the UI must not draw");
  assert.equal(thin.coverage, "insufficient");
  assert.equal(thin.commonStayDates, 3);
  assert.equal(thin.changePct, null);
  assert.equal(thin.direction, null);
  assert.ok(thin.points.every((point) => point.value == null));
  assert.deepEqual(model.trendSegments(thin.points), []);
});

test("insufficient market data never becomes a 0% line", () => {
  const view = model.dailyTrendView(region(fixture.missing_baseline));
  assert.equal(view.status, "insufficient");
  assert.equal(view.reason, "missing_baseline_snapshot");
  assert.match(view.reasonText, /7日前の観測がない/);
  assert.equal(view.market.points.length, 8);
  assert.ok(view.market.points.every((point) => point.value === null));
  assert.equal(view.market.changePct, null);
  assert.deepEqual(model.trendSegments(view.market.points), []);
  assert.ok(view.facilities.every((facility) => facility.coverage === "insufficient" && facility.points.every((point) => point.value === null)));
});

test("a missing value inside a series splits the line instead of being drawn as 0%", () => {
  const trend = clone(fixture.valid);
  trend.market.series[3].change_pct = null;
  const view = model.dailyTrendView(region(trend));
  assert.equal(view.market.points[3].value, null);
  const segments = model.trendSegments(view.market.points);
  assert.deepEqual(segments.map((segment) => segment.map((point) => point.index)), [[0, 1, 2], [4, 5, 6, 7]]);
});

test("missing export or a different cohort version is shown as insufficient", () => {
  const absent = model.dailyTrendView(region(undefined));
  assert.equal(absent.status, "insufficient");
  assert.equal(absent.reason, "not_exported");
  assert.deepEqual(model.trendSegments(absent.market.points), []);
  const stale = model.dailyTrendView(region({...clone(fixture.valid), cohort_version: "noboribetsu-v0"}));
  assert.equal(stale.status, "insufficient");
  assert.equal(stale.reason, "cohort_version_mismatch");
  assert.ok(stale.facilities.every((facility) => facility.coverage === "insufficient"));
});

test("trend axis keeps 0% visible and uses even steps", () => {
  assert.deepEqual(model.trendAxis([0, 0, 1, 1, 2, 3, 3, 4]).ticks, [6, 4, 2, 0, -2]);
  assert.deepEqual(model.trendAxis([null, null]).ticks, [4, 2, 0, -2]);
  const wide = model.trendAxis([0, -12, 18]);
  assert.ok(wide.ticks.includes(0));
  assert.ok(wide.max >= 18 && wide.min <= -12);
});

test("legacy Nagano regions are not offered as markets", () => {
  const phase1 = region(fixture.valid);
  const legacy = {code: "kamisuwa-onsen", name: "上諏訪温泉", properties: [{hotel_no: 1, name: "L"}], rates: [{hotel_no: 1, stay_date: "2026-10-12", meal_type: "two_meals", min_price_yen: 10000, status: "success"}]};
  const uncollected = {...region(undefined, {code: "atami", name: "熱海", cohort_version: "atami-v1"}), rates: []};
  const manifest = {regions: [
    {code: legacy.code, name: legacy.name},
    {code: phase1.code, name: phase1.name, cohort_version: "noboribetsu-v1"},
    {code: "atami", name: "熱海", cohort_version: "atami-v1"}
  ]};
  const selectable = model.selectableRegions(manifest, {regions: [legacy, phase1, uncollected]});
  assert.deepEqual(selectable.map((item) => item.code), ["noboribetsu-onsen"]);
});

// Runs the page script's control setup against a minimal DOM to check URL compatibility.
function loadControls(search) {
  const elements = new Map();
  // Like a real <select>, replacing the options selects the first one.
  const control = () => {
    let html = "";
    return {value: "", open: false, hidden: false, textContent: "", addEventListener() {}, setAttribute() {}, dispatchEvent() {},
      get innerHTML() { return html; },
      set innerHTML(value) { html = value; this.value = (/value="([^"]*)"/.exec(value) || [])[1] || ""; }};
  };
  const document = {querySelector(selector) {
    if (!elements.has(selector)) elements.set(selector, control());
    return elements.get(selector);
  }};
  const replaced = [];
  const source = fs.readFileSync(path.join(__dirname, "../js/hotel-price-trends.js"), "utf8");
  const instrumented = source.replace(/  init\(\);\s*\}\)\(\);\s*$/, `  manifest = window.__manifest; latest = window.__latest;
  populateControls(); syncUrl();
})();`);
  assert.notEqual(instrumented, source, "test hook must replace only the startup call");
  const legacy = {code: "kamisuwa-onsen", name: "上諏訪温泉", properties: [{hotel_no: 28001, name: "L"}], rates: [{hotel_no: 28001, stay_date: "2026-10-12", meal_type: "two_meals", min_price_yen: 10000, status: "success"}]};
  const phase1 = region(fixture.valid);
  phase1.rates.push(...CORE.map((hotel_no) => ({hotel_no, stay_date: "2026-10-20", meal_type: "two_meals", min_price_yen: 21000, plan_count: 1, status: "success"})));
  const window = {
    HotelPriceTrendsModel: model, addEventListener() {},
    history: {replaceState: (_state, _title, url) => replaced.push(url)},
    __manifest: {regions: [{code: legacy.code, name: legacy.name}, {code: phase1.code, name: phase1.name, cohort_version: "noboribetsu-v1"}]},
    __latest: {snapshot_date: "2026-10-11", regions: [legacy, phase1]}
  };
  vm.runInNewContext(instrumented, {document, window, location: {search, pathname: "/hotel-price-trends.html"}, URLSearchParams, Map, Set, Intl});
  return {get: (selector) => elements.get(selector), url: replaced.at(-1)};
}

test("a shared stay_date URL is carried into the price detail and kept in the URL", () => {
  const page = loadControls("?region=noboribetsu-onsen&hotel_no=12568&stay_date=2026-10-20&meal_type=breakfast");
  assert.equal(page.get("#hpt-region").value, "noboribetsu-onsen");
  assert.equal(page.get("#hpt-hotel").value, "12568");
  assert.equal(page.get("#hpt-stay-date").value, "2026-10-20");
  assert.equal(page.get("#hpt-detail-price").open, true);
  assert.equal(page.get("#hpt-meal").value, "breakfast");
  assert.equal(page.url, "/hotel-price-trends.html?region=noboribetsu-onsen&hotel_no=12568&stay_date=2026-10-20&meal_type=breakfast");
  assert.doesNotMatch(page.get("#hpt-region").innerHTML, /kamisuwa-onsen/);
});

test("URLs without a usable stay_date do not invent one, and legacy regions fall back to a Phase 1 market", () => {
  const plain = loadControls("?region=noboribetsu-onsen&hotel_no=30109&meal_type=two_meals");
  assert.equal(plain.get("#hpt-detail-price").open, false);
  assert.doesNotMatch(plain.url, /stay_date/);
  const stale = loadControls("?region=noboribetsu-onsen&stay_date=2020-01-01");
  assert.equal(stale.get("#hpt-detail-price").open, false);
  assert.doesNotMatch(stale.url, /stay_date/);
  const legacy = loadControls("?region=kamisuwa-onsen&hotel_no=28001&stay_date=2026-10-12");
  assert.equal(legacy.get("#hpt-region").value, "noboribetsu-onsen");
  assert.match(legacy.url, /region=noboribetsu-onsen/);
});
